---
# Update system before running playbook
pre_update: false

dotfiles:
  configure_dotfiles: true
  packages:
    - alacritty
    - chromium
    - kitty
    - neomutt
    - nvim
    - picom
    - polybar
    - ripgrep
    - scripts
    - tmux
    - wallpapers
    - x11
    - zathura
    - zsh

suckless:
  # Note that enabling this has no effect if running on a non-linux machine
  configure_suckless: true
  # Where to install programs to.
  # Destination is relative to user's $HOME
  installation_dir: .config
  # Git repository prefix to use.
  repo_prefix: https://github.com/toalaah
  # Which suckless programs to install.
  # Programs are cloned via the schema: {repo_prefix}/{program}.git
  programs:
    - dwm
    - st
    - dwmblocks
    - dmenu


configure_osx: true
shell:
  configure_default_shell: true
  default_shell_path: '/bin/zsh'
configure_git: true
configure_browser: true
configure_yarn: false
configure_npm: false
configure_go: false

# Clone and build neovim from source
neovim:
  configure_neovim: true
  # Set to a specific commit SHA, tag, branch, etc.
  # For latest stable release, set to 'stable'
  version: HEAD
  # Destination is relative to user's $HOME
  clone_destination: repos/neovim
  # Can be one of: Release | RelWithDebInfo | Debug
  build_type: Release

sudoers:
  configure_sudoers: true
  custom_config: |
    # Allow users in admin group to use sudo with no password
    %admin ALL=(ALL) NOPASSWD: ALL
    # Allow users in wheel group to use sudo with no password
    %wheel ALL=(ALL) NOPASSWD: ALL

configure_packages: false
homebrew:
  taps:
    - homebrew/core
    - homebrew/cask
  packages:
    - stow
  casks_dir: /Applications
  casks:
    - alacritty

npm_packages: []
pip_packages: []
