---
dotfiles:
  configure_dotfiles: true
  packages:
    - alacritty
    - chromium
    - kitty
    - neomutt
    - nvim
    - picom
    - polybar
    - ripgrep
    - scripts
    - tmux
    - wallpapers
    - x11
    - zathura
    - zsh
configure_window_manager: true
configure_osx: true
shell:
  configure_default_shell: true
  default_shell_path: '/bin/zsh'
configure_git: true
configure_browser: true
configure_yarn: false
configure_npm: false
configure_go: false
neovim:
  configure_neovim: false
  build_from_commit: 'HEAD'
sudoers:
  configure_sudoers: true
  custom_config: |
    # Allow users in admin group to use sudo with no password
    %admin ALL=(ALL) NOPASSWD: ALL
    # Allow users in wheel group to use sudo with no password
    %wheel ALL=(ALL) NOPASSWD: ALL

configure_packages: false
homebrew:
  taps:
    - homebrew/core
    - homebrew/cask
  packages:
    - stow
  casks_dir: /Applications
  casks:
    - alacritty

npm_packages: []
pip_packages: []
