---
# Update system before running playbook
pre_update: false
# Install dotfiles for the specified packages using GNU Stow
dotfiles:
  configure_dotfiles: true
  packages:
    - alacritty
    - chromium
    - kitty
    - neomutt
    - nvim
    - picom
    - polybar
    - ripgrep
    - scripts
    - tmux
    - wallpapers
    - x11
    - zathura
    - zsh
# Clone and build various suckless utilities
suckless:
  # Note that enabling this has no effect if running on a non-linux machine
  configure_suckless: true
  # Where to install programs to.
  # Destination is relative to user's $HOME
  installation_dir: .config
  # Git repository prefix to use.
  repo_prefix: https://github.com/toalaah
  # Which suckless programs to install.
  # Programs are cloned via the schema: {repo_prefix}/{program}.git
  programs:
    - dwm
    - st
    - dwmblocks
    - dmenu
# Set various osx defaults
configure_osx: true
# Configures the current user's default shell
shell:
  configure_default_shell: true
  default_shell_path: /bin/zsh
# Set various git aliases / preferences
configure_git: true
# Install ungoogled-chromium
configure_browser: true
# Configure the Yarn package manager
yarn:
  # Note that enabling this option implies the enabling npm.configure_npm
  configure_yarn: false
  version: v1.22.19
# Configure the NPM package manager
npm:
  configure_npm: false
# Clone and build neovim from source
neovim:
  configure_neovim: true
  # Set to a specific commit SHA, tag, branch, etc.
  # For latest stable release, set to 'stable'
  version: HEAD
  # Destination is relative to user's $HOME
  clone_destination: repos/neovim
  # Can be one of: Release | RelWithDebInfo | Debug
  build_type: Release
# Configure group properties in /etc/sudoers
sudoers:
  configure_sudoers: true
  custom_config: |
    # Allow users in admin group to use sudo with no password
    %admin ALL=(ALL) NOPASSWD: ALL
    # Allow users in wheel group to use sudo with no password
    %wheel ALL=(ALL) NOPASSWD: ALL
# Ensure that the specified packages are always installed
packages:
  configure_packages: true
  # Specify the package lists
  # Relative to base directory of the playbook
  package_lists:
    # Programs that are installed regardless of OS
    base: ./files/proglist-common.txt
    # Programs specific to Arch Linux machines
    arch: ./files/proglist-arch.txt
    # Programs specific to macOS machines
    osx: ./files/proglist-macos.txt
