---
- hosts: local

  vars_files:
      - config.yml

  pre_tasks:
  - name: update system (arch)
    become: true
    community.general.pacman:
      update_cache: true
      upgrade: true
    when: pre_update and ansible_facts['os_family'] == "Archlinux"

  - name: update system (mac-os)
    community.general.homebrew:
      update_homebrew: true
      upgrade: true
    when: pre_update and ansible_facts['os_family'] == "Darwin"

  tasks:
    - name: setup base packages
      include_tasks: tasks/packages.yml
      vars:
        common: "{{ lookup('file', './files/proglist-common.txt').splitlines() }}"
        arch: "{{ lookup('file', './files/proglist-arch.txt').splitlines() }}"
        macos: "{{ lookup('file', './files/proglist-macos.txt').splitlines() }}"
      when: configure_packages

    - name: setup osx defaults
      include_tasks: tasks/osx-defaults.yml
      when: configure_osx and ansible_facts['os_family'] == "Darwin"

    - name: set user shell
      include_tasks: tasks/shell.yml
      when: shell.configure_default_shell

    - name: configure git config
      include_tasks: tasks/git.yml
      when: configure_git

    - name: configure suckless programs
      include_tasks: tasks/suckless.yml
      when: suckless.configure_suckless and not ansible_facts['os_family'] == "Darwin"

    - name: clone and symlink dotfiles
      include_tasks: tasks/dotfiles.yml
      when: dotfiles.configure_dotfiles

    - name: configure sudoers
      include_tasks: tasks/sudoers.yml
      when: sudoers.configure_sudoers

    - name: setup neovim
      include_tasks: tasks/neovim.yml
      when: neovim.configure_neovim

    - name: install chromium
      include_tasks: tasks/chromium.yml
      when: configure_browser
