- hosts: localhost
  # pre_tasks:
  # - name: Update system
  #   become: true
  #   pacman:
  #     update_cache: true
  #     upgrade: true
  #   tags:
  #     - install
  #     - core
  tasks:
    - include_tasks: tasks/base.yml
      name: Setup Base Packages

    - include_tasks: tasks/osx-defaults.yml
      name: Setup OSX Defaults
      when: ansible_facts['os_family'] == "Darwin"

    - include_tasks: tasks/git.yml
      name: Configure git config

    - include_tasks: tasks/suckless.yml
      name: Configure suckless programs
      when: ansible_facts['os_family'] == "Archlinux" or ansible_facts['os_family'] == "Ubuntu"

    - include_tasks: tasks/dotfiles.yml
      name: Clone and symlink dotfiles

    # - include: tasks/packages.yml
    # - include: tasks/node.yml
    # - include: tasks/go.yml
    # - include: tasks/nvim.yml
