---
- hosts: localhost
  pre_tasks:
  - name: update system (arch)
    become: true
    community.general.pacman:
      update_cache: true
      upgrade: true
    when: ansible_facts['os_family'] == "Archlinux"

  - name: update system (mac-os)
    community.general.homebrew:
      update_homebrew: true
      upgrade: true
    when: ansible_facts['os_family'] == "Darwin"

  tasks:
    - name: setup base packages
      include_tasks: tasks/packages.yml
      vars:
        common: "{{ lookup('file', './files/proglist-common.txt').splitlines() }}"
        arch: "{{ lookup('file', './files/proglist-arch.txt').splitlines() }}"
        macos: "{{ lookup('file', './files/proglist-macos.txt').splitlines() }}"

    - name: setup osx defaults
      include_tasks: tasks/osx-defaults.yml
      when: ansible_facts['os_family'] == "Darwin"

    - name: set user shell
      include_tasks: tasks/shell.yml

    - name: configure git config
      include_tasks: tasks/git.yml

    - name: configure suckless programs
      include_tasks: tasks/suckless.yml
      when: ansible_facts['os_family'] == "Archlinux" or ansible_facts['os_family'] == "Ubuntu"

    - name: clone and symlink dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: install chromium
      include_tasks: tasks/chromium.yml
