---
- name: clone configurations
  ansible.builtin.git:
    repo: 'git@github.com:Toalaah/config.git'
    dest: "{{ lookup('env', 'HOME') }}/.local/dotfiles"
    recursive: yes # fetch all submodules
    track_submodules: yes
    accept_newhostkey: yes
    version: HEAD

- name: stow dotfiles
  shell: "stow --verbose=1 --dir=$HOME/.local/dotfiles --target=$HOME {{ item.name }}"
  loop:
    - { name: 'alacritty' }
    - { name: 'bat' }
    - { name: 'chromium' }
    - { name: 'nvim' }
    - { name: 'picom' }
    - { name: 'scripts' }
    - { name: 'tmux' }
    - { name: 'wallpapers' }
    - { name: 'x11' }
    - { name: 'zathura' }
    - { name: 'zsh' }
  register: stow
  changed_when: "'LINK' in stow.stderr"
