---
- name: clone configurations
  ansible.builtin.git:
    repo: 'https://github.com/toalaah/config.git'
    dest: "{{ lookup('env', 'HOME') }}/.local/dotfiles"
    recursive: true # fetch all submodules
    track_submodules: true
    accept_newhostkey: true

- name: stow dotfiles
  ansible.builtin.shell: "stow --verbose=1 --restow --dir=$HOME/.local/dotfiles --target=$HOME {{ item.name }}"
  loop:
    - { name: 'alacritty' }
    - { name: 'bat' }
    - { name: 'chromium' }
    - { name: 'kitty' }
    - { name: 'neomutt' }
    - { name: 'nvim' }
    - { name: 'picom' }
    - { name: 'polybar' }
    - { name: 'scripts' }
    - { name: 'tmux' }
    - { name: 'wallpapers' }
    - { name: 'x11' }
    - { name: 'zathura' }
    - { name: 'zsh' }
  register: stow
  changed_when: "'reverts previous action' not in stow.stderr"
  failed_when: "'ERROR' in stow.stderr"
