---
- name: set variables
  ansible.builtin.set_fact:
    user_email: "{{ git.user_email }}"
    user_name: "{{ git.user_name }}"
    default_branch_name: "{{ git.default_branch_name }}"
    config_path: "{{ git.config_path }}"

- name: setup git config
  block:
  - name: configure git
    git_config:
      name: "{{ item.name }}"
      scope: "file"
      value: "{{ item.value }}"
      file: "{{ config_path }}"
    loop:
      - { name: 'alias.lg',              value: 'log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative' }
      - { name: 'alias.s',               value: 'status --short' }
      - { name: 'commit.gpgsign',        value: 'true' }
      - { name: 'core.editor',           value: 'nvim' }
      - { name: 'core.excludesFile',     value: '~/.config/git/ignore' }
      - { name: 'core.hooksPath',        value: '~/.config/git/hooks' }
      - { name: 'core.pager',            value: 'delta' }
      - { name: 'credential.provider',   value: 'generic' }
      - { name: 'init.defaultBranch',    value: '{{ default_branch_name }}' }
      - { name: 'pull.rebase',           value: 'true' }
      - { name: 'push.autoSetupRemote',  value: 'true' }
      - { name: 'rebase.autoStash',      value: 'true' }
      - { name: 'user.email',            value: '{{ user_email }}' }
      - { name: 'user.name',             value: '{{ user_name }}'}
      - { name: 'interactive.diffFilter',value: 'delta --color-only'}
      - { name: 'delta.syntax-theme',    value: 'gruvbox'}
      - { name: 'delta.side-by-side',    value: 'false'}
      - { name: 'merge.conflictStyle',   value: 'diff3'}
      - { name: 'diff.colorMoved',       value: 'default'}
