---
- block:
  - name: configure git
    git_config: { name: "{{ item.name }}", scope: "{{ item.scope }}", value: "{{ item.value }}" }
    loop:
      - { name: 'init.defaultBranch',  scope: 'global', value: 'master' }
      - { name: 'user.email',          scope: 'global', value: 'samuel.kunst@gmail.com' }
      - { name: 'user.name',           scope: 'global', value: 'Samuel Kunst'}
      - { name: 'alias.ci',            scope: 'global', value: 'commit' }
      - { name: 'alias.s',             scope: 'global', value: 'status' }
      - { name: 'alias.lg',            scope: 'global', value: 'log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative' }
      - { name: 'commit.gpgsign',      scope: 'global', value: 'true' }
      - { name: 'credential.provider', scope: 'global', value: 'generic' }
      - { name: 'pull.rebase',         scope: 'global', value: 'true' }
      - { name: 'rebase.autoStash',    scope: 'global', value: 'true' }
      - { name: 'rebase.autoStash',    scope: 'global', value: 'true' }
      - { name: 'core.editor',         scope: 'global', value: 'nvim' }
      - { name: 'core.excludesFile',   scope: 'global', value: '~/.config/git/ignore' }
      - { name: 'core.hooksPath',      scope: 'global', value: '~/.config/git/hooks' }
      - { name: 'core.pager',          scope: 'global', value: 'bat --style=plain' }

