---
- name: set variables
  ansible.builtin.set_fact:
    user_email: "{{ git.user_email }}"
    user_name: "{{ git.user_name }}"
    default_branch_name: "{{ git.default_branch_name }}"
    config_path: "{{ git.config_path }}"

- name: setup git config
  block:
  - name: configure git
    git_config:
      name: "{{ item.name }}"
      scope: "{{ item.scope }}"
      value: "{{ item.value }}"
      file: "{{ config_path }}"
    loop:
      - { name: 'alias.ci',             scope: 'global', value: 'commit' }
      - { name: 'alias.lg',             scope: 'global', value: 'log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative' }
      - { name: 'alias.s',              scope: 'global', value: 'status --short' }
      - { name: 'commit.gpgsign',       scope: 'global', value: 'true' }
      - { name: 'core.editor',          scope: 'global', value: 'nvim' }
      - { name: 'core.excludesFile',    scope: 'global', value: '~/.config/git/ignore' }
      - { name: 'core.hooksPath',       scope: 'global', value: '~/.config/git/hooks' }
      - { name: 'core.pager',           scope: 'global', value: 'bat --style=plain' }
      - { name: 'credential.provider',  scope: 'global', value: 'generic' }
      - { name: 'init.defaultBranch',   scope: 'global', value: '{{ default_branch_name }}' }
      - { name: 'pull.rebase',          scope: 'global', value: 'true' }
      - { name: 'push.autoSetupRemote', scope: 'global', value: 'true' }
      - { name: 'rebase.autoStash',     scope: 'global', value: 'true' }
      - { name: 'rebase.autoStash',     scope: 'global', value: 'true' }
      - { name: 'user.email',           scope: 'global', value: '{{ user_email }}' }
      - { name: 'user.name',            scope: 'global', value: '{{ user_name }}'}
