---
- name: install keyd
  kewlfft.aur.aur:
    name: keyd
    state: present

- name: enable / start keyd daemon
  ansible.builtin.systemd:
      name: keyd
      state: started
      enabled: yes
  become: true

- name: configure keyd
  ansible.builtin.template:
    src: files/keyd.conf
    dest: /etc/keyd/default.conf
  become: true

