---
- name: install common packages (arch)
  become: true
  kewlfft.aur.aur:
    name:
      - "lazydocker"
      - "lazygit"
      - "ungoogled-chromium"
      - "alacritty"
      - "bat"
      - "clang"
      - "cowsay"
      - "docker"
      - "docker"
      - "docker-compose"
      - "exa"
      - "fd"
      - "feh"
      - "fzf"
      - "git"
      - "glow"
      - "gnupg"
      - "go"
      - "htop"
      - "jq"
      - "lf"
      - "mpv"
      - "neofetch"
      - "npm"
      - "openssh"
      - "pass"
      - "ripgrep"
      - "shellcheck"
      - "stow"
      - "tldr"
      - "tmux"
      - "unzip"
      - "zoxide"
      - "zsh"
  when: ansible_facts['os_family'] == "Archlinux"

- name: install common packages (mac-os)
  community.general.homebrew:
    name:
      - "alacritty"
      - "bat"
      - "clang"
      - "cowsay"
      - "docker"
      - "docker"
      - "docker-compose"
      - "exa"
      - "fd"
      - "feh"
      - "fzf"
      - "git"
      - "glow"
      - "gnupg"
      - "go"
      - "htop"
      - "jq"
      - "lazydocker"
      - "lazygit"
      - "lf"
      - "mpv"
      - "neofetch"
      - "npm"
      - "openssh"
      - "pass"
      - "ripgrep"
      - "shellcheck"
      - "stow"
      - "tldr"
      - "tmux"
      - "unzip"
      - "zoxide"
      - "zsh"
  when: ansible_facts['os_family'] == "Darwin"

- name: install additional packages (arch only)
  become: true
  kewlfft.aur.aur:
    name:
      - "nordvpn-bin"
      - "binutils"
      - "dhcpcd"
      - "dunst"
      - "feh"
      - "mpv"
      - "ncdu"
      - "nvidia"
      - "nvidia-settings"
      - "nvidia-utils"
      - "opencl-nvidia"
      - "pacman-contrib"
      - "pipewire"
      - "pipewire-alsa"
      - "pipewire-pulse"
      - "qbittorrent"
      - "redshift"
      - "scrot"
      - "slock"
      - "ttf-arphic-uming"
      - "ttf-baekmuk"
      - "ttf-joypixels"
      - "ttf-symbola"
      - "unclutter"
      - "xclip"
      - "xcompmgr"
      - "xdotool"
      - "xdotool"
      - "xorg-server"
      - "xorg-server-devel"
      - "xorg-xinit"
      - "xorg-xrandr"
      - "xorg-xset"
      - "xurls"
      - "yay-bin"
      - "zathura"
      - "zathura-pdf-mupdf"
  when: ansible_facts['os_family'] == "Archlinux"

- name: install additional packages (mac-os only)
  community.general.homebrew:
    name:
      - "the-unarchiver"
      - "vlc"
  when: ansible_facts['os_family'] == "Darwin"


