---
- name: install packages (arch linux)
  when: ansible_facts['os_family'] == "Archlinux"
  block:
  - name: install common packages
    kewlfft.aur.aur:
      name: "{{ common }}"
  - name: install additional packages
    kewlfft.aur.aur:
      name: "{{ arch }}"

- name: install packages (mac-os)
  when: ansible_facts['os_family'] == "Darwin"
  block:
  - name: install common packages
    community.general.homebrew:
      name: "{{ common }}"
  - name: install additional packages
    community.general.homebrew:
      name: "{{ macos }}"
