---
- name: set variables
  ansible.builtin.set_fact:
    base: "{{ lookup('file', packages.package_lists.base).splitlines() }}"
    arch: "{{ lookup('file', packages.package_lists.arch).splitlines() }}"
    osx: "{{ lookup('file', packages.package_lists.osx).splitlines() }}"

- name: install packages (arch linux)
  when: ansible_facts['os_family'] == "Archlinux"
  block:
  - name: install common packages
    kewlfft.aur.aur:
      name: "{{ base }}"
  - name: install additional packages
    kewlfft.aur.aur:
      name: "{{ arch }}"

- name: install packages (mac-os)
  when: ansible_facts['os_family'] == "Darwin"
  block:
  - name: install common packages
    community.general.homebrew:
      name: "{{ base }}"
  - name: install additional packages
    community.general.homebrew:
      name: "{{ osx }}"
