---
- name: configure pacman
  block:
    - name: enable multilib repository
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include= /etc/pacman.d/mirrorlist
      become: true
    - name: enable color output
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: '^#\s*Color.*$'
        replace: Color
      become: true
    - name: configure max parallel downloads
      ansible.builtin.replace:
        path: /etc/pacman.conf
        regexp: '^#\s*ParallelDownloads.*$'
        replace: ParallelDownloads={{ pacman.max_parallel_downloads }}
      become: true
