---
- name: set variables
  ansible.builtin.set_fact:
    installation_dir: "{{ lookup('env', 'HOME') }}/{{ suckless.installation_dir }}"

- name: clone suckless programs
  ansible.builtin.git: { repo: "{{ suckless.repo_prefix }}/{{ item }}.git", dest: "{{ installation_dir }}/{{ item }}", accept_newhostkey: 'yes' }
  with_items: "{{ suckless.programs }}"

- name: build suckless programs
  make: { chdir: "{{ installation_dir }}/{{ item.name }}", target: install }
  loop: "{{ progs }}"
  become: true
