---
- name: set variables
  ansible.builtin.set_fact:
    installation_dir: "{{ lookup('env', 'HOME') }}/.config"
    progs:
      - { name: 'dwm',       repo: 'git@github.com:Toalaah/dwm.git' }
      - { name: 'st',        repo: 'git@github.com:Toalaah/st.git' }
      - { name: 'dwmblocks', repo: 'git@github.com:Toalaah/dwmblocks.git' }
      - { name: 'dmenu',     repo: 'git@github.com:Toalaah/dmenu.git' }

- name: clone suckless programs
  ansible.builtin.git: { repo: "{{ item.repo }}", dest: "{{ installation_dir }}/{{ item.name }}", accept_newhostkey: 'yes' }
  loop: "{{ progs }}"

- name: build suckless programs
  make: { chdir: "{{ installation_dir }}/{{ item.name }}", target: install }
  loop: "{{ progs }}"
  become: true
